# Generated by Django 3.1.2 on 2020-12-05 06:07

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=150, null=True, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, db_column='slug', editable=False, null=True, populate_from='name', unique_with=('created_dt__month',))),
                ('publish_status', models.BooleanField(db_column='publish_status', default=True, verbose_name='Publish Status')),
                ('logo', models.ImageField(blank=True, db_column='logo', null=True, upload_to='business/delivery/', verbose_name='Logo')),
                ('deep_link_url', models.CharField(blank=True, db_column='deep_link_url', max_length=150, null=True, verbose_name='Deep Link URL')),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_link_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Delivery Master',
                'db_table': 'Delivery_Master',
            },
        ),
    ]
