# Generated by Django 3.1.2 on 2020-12-05 11:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage_delivery_partner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery_Master',
            new_name='Delivery_Partner',
        ),
    ]
