# Generated by Django 3.1.3 on 2020-12-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_delivery_partner', '0002_auto_20201205_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_partner',
            name='logo',
            field=models.ImageField(blank=True, db_column='logo', default='defalut_partner_logo.png', null=True, upload_to='business/delivery/', verbose_name='Logo'),
        ),
    ]
