"""
Django settings for BestofProject project.

Generated by 'django-admin startproject' using Django 3.1.3.
Pradeep
For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')
TEMPLATES_DIR = BASE_DIR / 'templates'
STATIC_DIR = BASE_DIR / 'static'
MEDIA_DIR = BASE_DIR / 'media'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_gtm6$6#we5r08_m3%%8eg$yt#5^kz(8-&-fm@zq552vioxe1t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # extra install app
    'rest_framework',
    'import_export',
    # add developer some created application
    'custom_user.apps.CustomUserConfig',
    # install app for API
    'user_app.apps.UserAppConfig',
    'update_detail.apps.UpdateDetailConfig',
    'business_detail.apps.BusinessDetailConfig',
    'category_app.apps.CategoryAppConfig',
    'posts.apps.PostsConfig',
    'notification.apps.NotificationConfig',
    # install app for Admin
    'audits.apps.AuditsConfig',
    'manage_food_category.apps.ManageFoodCategoryConfig',
    'voting.apps.VotingConfig',
    'addition_photo.apps.AdditionPhotoConfig',
    'post_creation.apps.PostCreationConfig',
    'manage_posts.apps.ManagePostsConfig',
    'manage_user.apps.ManageUserConfig',
    'manage_business.apps.ManageBusinessConfig',
    'admin_setting.apps.AdminSettingConfig',
    'manage_delivery_partner.apps.ManageDeliveryPartnerConfig',
]

# User substitution
# https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#auth-custom-user

AUTH_USER_MODEL = 'custom_user.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BestofProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BestofProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


REST_FRAMEWORK = {

    'EXCEPTION_HANDLER': 'custom_user.utils.custom_exception_handler',


    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 1,
    'DEFAULT_THROTTLE_RATES': {
        'burst': '6000/min',
        'sustained': '100000/day'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'static/'
STATICFILES_DIRS = [
    STATIC_DIR
]



#  code for email send form gmail account
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtpout.secureserver.net'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'gaurav@digimonk.net'
EMAIL_HOST_PASSWORD = 'digimonk@123'


BASE_URL = "http://203.190.153.22:8888/"
IMAGE_BASE_URL = "http://203.190.153.22:8888"

# Admin Login and Logout Urls.
LOGIN_URL = BASE_URL+'admin/login'
LOGIN_REDIRECT_URL = BASE_URL+'admin/'
LOGOUT_REDIRECT_URL = BASE_URL+'admin/login'


# Yelp information.
YELP_API_KEY = 'XkjWF9GSy19xRS_yytCtISMaViqsPuXGmQiTzzAdcRHHNJmISD9bnHisRb8tgF5H7xVuMnbcybxOvEHHM7o91yTFKcGO7KrERhOSMS9NtRiPQNq9tCxMl61oD10pXnYx'
YELP_HEADERS = {'Authorization': 'Bearer %s' % YELP_API_KEY}
YELP_URL = 'https://api.yelp.com/v3/businesses/search'
YELP_ID_URL = 'https://api.yelp.com/v3/businesses/'

MEDIA_URL = '/media/'
MEDIA_ROOT = MEDIA_DIR
