# Generated by Django 3.1.3 on 2020-11-07 13:29

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('custom_user', '0002_auto_20201107_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
