# Generated by Django 3.1.3 on 2020-11-07 13:34

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('custom_user', '0003_auto_20201107_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'User Info'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='User_Info',
        ),
    ]
