# Generated by Django 3.1.3 on 2020-11-17 08:12

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('custom_user', '0002_auto_20201112_1137'),
        ('custom_user', '0004_auto_20201107_1334'),
    ]

    operations = [
    ]
