# Generated by Django 3.1.3 on 2020-11-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='publish_status',
            field=models.BooleanField(db_column='publish_status', default=True, verbose_name='Publish Status'),
        ),
    ]
