# Generated by Django 3.1.3 on 2021-01-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search_Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, db_column='keyword', max_length=250, null=True, verbose_name='Keyword')),
                ('total_search', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Search Keyword',
                'db_table': 'Search_Keyword',
            },
        ),
    ]
