# Generated by Django 3.1.3 on 2021-01-06 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_keyword',
            name='total_search',
        ),
        migrations.AddField(
            model_name='search_keyword',
            name='created_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
