# Generated by Django 3.1.3 on 2020-11-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_detail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_categories',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='business_categories',
            name='name',
        ),
        migrations.RemoveField(
            model_name='business_details',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='business_photos',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='business_time',
            name='created_by',
        ),
        migrations.AddField(
            model_name='business_categories',
            name='alias',
            field=models.CharField(blank=True, db_column='alias', max_length=50, null=True, verbose_name='Alias'),
        ),
        migrations.AddField(
            model_name='business_categories',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=50, null=True, verbose_name='Title'),
        ),
    ]
