# Generated by Django 3.1.3 on 2020-11-18 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_detail', '0003_auto_20201117_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_categories',
            name='Business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_category_for', to='business_detail.business_details'),
        ),
    ]
