# Generated by Django 3.1.3 on 2020-11-21 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_auto_20201121_0948'),
        ('business_detail', '0005_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Tag_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_post_for', to='category_app.tag'),
        ),
    ]
