# Generated by Django 3.1.3 on 2020-11-21 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category_app', '0002_auto_20201121_0948'),
        ('business_detail', '0006_auto_20201121_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, db_column='post_image', null=True, upload_to='business/post/', verbose_name='Post Image')),
                ('comment', models.CharField(blank=True, db_column='comment', max_length=250, null=True, verbose_name='Comment')),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('Business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_post_for', to='business_detail.business_details')),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_post_for', to='category_app.category')),
                ('Tag_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_post_for', to='category_app.tag')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_created_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Business Posts',
                'db_table': 'Business_Posts',
            },
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
