# Generated by Django 3.1.3 on 2020-11-23 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_detail', '0008_post_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_activity',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_activity_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
