# Generated by Django 3.1.3 on 2020-12-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_detail', '0009_auto_20201123_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_details',
            name='total_like',
            field=models.CharField(blank=True, db_column='total_like', max_length=50, null=True, verbose_name='Total Like'),
        ),
        migrations.AddField(
            model_name='business_details',
            name='total_vote',
            field=models.CharField(blank=True, db_column='total_vote', max_length=50, null=True, verbose_name='Total Vote'),
        ),
    ]
