# Generated by Django 3.1.3 on 2020-12-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_detail', '0010_auto_20201204_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_posts',
            name='total_vote',
            field=models.CharField(blank=True, db_column='total_vote', max_length=50, null=True, verbose_name='Total Vote'),
        ),
    ]
