# Generated by Django 3.1.3 on 2020-12-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_detail', '0012_remove_business_posts_total_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_posts',
            name='owner_id',
            field=models.CharField(blank=True, db_column='owner_id', max_length=250, null=True, verbose_name='Owner ID'),
        ),
    ]
