# Generated by Django 3.1.3 on 2020-12-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_detail', '0013_business_posts_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_posts',
            name='publish_status',
            field=models.BooleanField(db_column='publish_status', default=True, verbose_name='Publish Status'),
        ),
        migrations.AddField(
            model_name='business_posts',
            name='total_vote',
            field=models.CharField(blank=True, db_column='total_vote', default='0', max_length=50, null=True, verbose_name='Total Vote'),
        ),
    ]
