# Generated by Django 3.1.2 on 2020-12-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_delivery_partner', '0003_auto_20201216_1314'),
        ('business_detail', '0014_auto_20201215_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_details',
            name='dilevery_partner',
            field=models.ManyToManyField(blank=True, db_column='dilevery_partner', max_length=350, null=True, to='manage_delivery_partner.Delivery_Partner'),
        ),
    ]
