# Generated by Django 3.1.2 on 2020-12-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_detail', '0016_auto_20201225_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_details',
            name='image_url',
            field=models.CharField(blank=True, db_column='image_url', max_length=250, null=True, verbose_name='Image URL'),
        ),
    ]
