# Generated by Django 3.1.3 on 2020-12-31 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_detail', '0017_auto_20201225_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remove_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, db_column='type', max_length=50, null=True, verbose_name='Type')),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('Post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remove_post_for', to='business_detail.business_posts')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remove_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Remove Activity',
                'db_table': 'Remove_Activity',
            },
        ),
    ]
