# Generated by Django 3.1.3 on 2021-01-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_detail', '0018_remove_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_photos',
            name='set_as_default',
            field=models.BooleanField(db_column='set_as_default', default=False, verbose_name='Set as Default'),
        ),
    ]
