# Generated by Django 3.1.3 on 2021-01-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_detail', '0019_business_photos_set_as_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_photos',
            name='business_image',
            field=models.ImageField(blank=True, db_column='business_image', null=True, upload_to='business/image/', verbose_name='Business Image'),
        ),
    ]
